spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    platform: h2
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true